### ISSUE TITLE
Release build doesn't seem to work

### ISSUE THREAD

**Issue by avi-cenna** [timrobertsdev/hotcorners#13] opened 2024-07-20 15:15 UTC
This is a nice tool, but the release build doesn't seem to work for some reason.

I did both `cargo build` and `cargo build --release`. When I ran the release executable with `start target/release/hotcorners.exe` nothing happens when I move my mouse to the top left corner. However, when I run the debug build with `start target/debug/hotcorners.exe` it works as expected.

**Comment by timrobertsdev** [comment] 2024-07-21 15:53
Interesting. Reproduced on my machines. Thanks for reporting, I'll have to look into this.

**Comment by timrobertsdev** [comment] 2024-07-21 17:12
Even more fun, anything above `opt-level = 0` seems to be causing incorrect parameters being passed to our callback function that gets registered with Windows.

**Comment by timrobertsdev** [comment] 2024-07-21 18:39
Fixed in the latest commit! Seems like I introduced some UB that wasn't actually an issue until 1.78.

**Closed as completed by timrobertsdev** 2024-07-21 18:39 UTC
